[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
