[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip3 install --upgrade pip", "pip3 install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
