[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
